apiVersion: v1
kind: Secret
metadata:
  name: "database-mysql-person-secret"
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "cm9vdA=="
  MYSQL_USER: "d2VzbGV5b3NhbnRvczkxCg=="
  MYSQL_PASSWORD: "d29zdGVjbm9sb2dpYQo="
