apiVersion: v1
kind: Service
metadata:
  name: "database-mysql-person-service"
spec:
  selector:
    app: "database-mysql-person"
  ports:
    - name: "database-mysql-person-service"
      port: 3306
      targetPort: 3306
  clusterIP: None