apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ms-person"
  labels:
    app: "ms-person"
spec:
  selector:
    matchLabels:
      app: "ms-person"
  replicas: 1
  template:
    metadata:
      labels:
        app: "ms-person"
    spec:
      containers:
        - name: "ms-person"
          image: wesleyosantos91/ms-person:v1
