apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ms-person"
  labels:
    app: "ms-person"
spec:
  selector:
    matchLabels:
      app: "ms-person"
  replicas: 1
  template:
    metadata:
      labels:
        app: "ms-person"
    spec:
      containers:
        - name: "ms-person"
          image: wesleyosantos91/ms-person:v1.6
          startupProbe:
            httpGet:
              port: 8181
              path: /actuator/health/liveness
            periodSeconds: 3
            failureThreshold: 30
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8181
            periodSeconds: 3
            timeoutSeconds: 7
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8181
            periodSeconds: 6
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: ms-person-configmap
            - secretRef:
                name: ms-person-secret
          ports:
            - containerPort: 8181
